export { default as NotFound } from './NotFound'
export { default as Home } from './Home'
export { default as AboutUs } from './AboutUs'
export { default as Contacts } from './Contacts'
export { default as DailyLife } from './DailyLife'
export { default as Services } from './Services'
export { default as Structure } from './Structure'
